server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kjykjy950103/spring-cloud-config-repository
          username: kjykjy950103
          password: a1b2c3d4e5~
      enabled: false

