server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kjykjy950103/spring-cloud-config-repository
      enabled: false

